name: Test
on: [push]
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: https://github.com/actions/checkout@v4
      - name: Install Pylint & pandas
        run: apt-get update && apt-get install -y pylint python3-pandas
      - name: Run Pylint
        run: pylint app.py
