name: Test
on: [push]
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3 python3-pip
          python3 -m pip install --upgrade pip
          pip3 install pylint pandas
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
