name: Test
on: [push]
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pandas
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
